Added support for 72 and 96PPI images
usnistgov/NFIQ2 pull request #163
Opened 2021-02-15 18:13 UTC by afiglarz

~DRAFT~

Addresses Issue #154 

Added check for 72 and 96PPI images, allowing users to process these images without requiring a resample. 

*Need additional test images to confirm that this actually works. Used test 500PPI image resampled to 96PPI. NFIQ2 fails with a score of 255. - Likely because the image was of such poor quality, but need to confirm with additional prints.

2021-02-16 14:55 UTC, afiglarz commented
Removed support for 96 PPI images because biomeval does not support them in the same way as 72 PPI images.

2021-03-02 14:40 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +	// resolution, or are 72PPI.
```suggestion
	// resolution, or assumed to be that resolution.
```

2021-03-02 14:52 UTC, gfiumara commented
* `-F` should treat `defaultDPI` images as `requiredDPI` + should include a note that it was performed in CSV output. Please implement.
 * Ensure that errors for single images are not output in CSV format.

2021-03-02 14:53 UTC, gfiumara requested changes
* `-F` should treat `defaultDPI` images as `requiredDPI` + should include a note that it was performed in CSV output. Please implement.
 * Ensure that errors for single images are not output in CSV format.

2021-03-04 20:08 UTC, gfiumara requested changes

2021-03-04 20:08 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/include/nfiq2/tool/nfiq2_ui_refresh.h
> +bool quantizeCheck();
```suggestion
bool askToQuantize();
```

2021-03-04 20:08 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/include/nfiq2/tool/nfiq2_ui_refresh.h
> +bool resampleCheck(const std::string &name, const uint16_t imageDPI,
```suggestion
bool askToResample(const std::string &name, const uint16_t imageDPI,
```

2021-03-04 20:08 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/include/nfiq2/tool/nfiq2_ui_refresh.h
> +bool defaultCheck(const std::string &name, const uint16_t defaultDPI,
```suggestion
bool askToResampleIfNoResolution(const std::string &name, const uint16_t defaultDPI,
```

Hmm, maybe you can think of a better name.

2021-03-04 20:08 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +		resampled, singleImage };
If you're going to use this struct, use it all the time. You now have `resampled` (non-`const`) and `imageProps.resampled` (`const`), etc. You _will_ screw this up. I'm not even going to check the usage here.

Make this non-const and declare it at the top.

2021-03-04 20:08 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +				    imageProps);
`resampled` here is `true` but `imageProps.resampled` is `false`.

2021-03-04 20:08 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +			if (imageDPI == defaultDPI) {
`defaultCheck` probably lets you get rid of this if statement?

2021-03-17 17:04 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +	}
If you're passing this is a parameter, and it has to be 72, then don't ask for it as a parameter?

2021-03-17 17:04 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +				if (e.errorWasHandled()) {
I'd argue _you_ don't have to do this, but it doesn't hurt. Just an FYI. You know your logger isn't `nullptr` (right?).

2021-03-17 17:04 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +						if (e.errorWasHandled()) {
Same comment.

2021-03-17 17:09 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +    std::shared_ptr<NFIQ2UI::Log> logger = nullptr)
Did this compile? Default params go in the header.

```suggestion
    std::shared_ptr<NFIQ2UI::Log> logger)
```

2021-03-17 17:09 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +	if (logger != nullptr) {
Why duplicate all this code? Check for logger in the exception handlers.

2021-03-23 12:25 UTC, gfiumara commented on NFIQ2/NFIQ2Algorithm/src/tool/nfiq2_ui_refresh.cpp
> +		errStr = errStr.append(e.what()) + "'";
Until update:
```suggestion
	} catch (NFIR::Miscue &e) {
		std::string errStr = "'NFIR resample error: ";
		errStr = errStr.append(e.message()) + "'";
```

2021-03-23 12:55 UTC, merged